## Zach Holcomb Statistical Analysis Portfolio

#### [Linear Regression Weather Prediction](weather_prediction/MySimpleLinearRegression-1.html)

Used Linear Regression to observe the relationship between the date and the tempurature over the course of 2 months. 

#### [Multiple Linear Regression Car Pricing Analysis](car_prices/CarPrices-1.html)

Used multiple linear regression to find the variable(s) responsible for pricing differences between Deville Cadillacs.

#### [Logistic Regression Dungeons and Dragons Odds Assesment](dnd_odds/MyLogisticRegression-1.html)

Used logistic regression to experimentaly determine the odds of defeating an enemy in the game Dungeons and Dragons with a specific spell.

#### [T-test High School Athlete vs Non-Athlete Reaction Time Comparison](athletes/HighSchoolSeniors-2.html)

Used t-tests to determine if a relationship exists between a high school student's participation in sports and their reaction time.

#### [T-Test BYU-Idaho Parking Analysis](byui_parking/Parking.html)

Analyzed historic data for parking usage for BYU-Idaho to help decide whether to sell more permits each semester.